import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getLocale, getMessages, getTimeZone } from "next-intl/server";
import "./globals.css";
import SwRegister from "./swRegister";
import AppShell from "@/components/AppShell";
import AppProviders from "@/components/AppProviders";
import { isRtl, normalizeLocale, type AppLocale } from "@/i18n/config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "O' Petit Frais",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
  applicationName: "O' Petit Frais",
  appleWebApp: {
    capable: true,
    title: "O' Petit Frais",
    statusBarStyle: "default",
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: [{ url: "/icons/icon-192.png" }, { url: "/icons/icon-512.png" }],
    apple: [{ url: "/icons/icon-512.png" }],
  },
};

export const viewport = {
  themeColor: "#16a34a",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = normalizeLocale(await getLocale()) as AppLocale;
  const messages = await getMessages();
  const timeZone = await getTimeZone();
  const dir = isRtl(locale) ? "rtl" : "ltr";

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <AppProviders locale={locale} messages={messages as Record<string, unknown>} timeZone={timeZone}>
          <SwRegister />
          <AppShell>{children}</AppShell>
        </AppProviders>
      </body>
    </html>
  );
}
